sudo: required
services:
  - docker


before_install:
  - docker build -t debasishk/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true debasishk/multi-docker npm test 

after_success:
  - docker build -t debasishk/multi-client ./client
  - docker build -t debasishk/multi-nginx ./ngnex
  - docker build -t debasishk/multi-server ./server
  - docker build -t debasishk/multi-worker ./worker

# Take those images and push them to docker hub
