sudo: required
services:
  - docker


before_install:
  - docker build -t debasishk/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true debasishk/multi-docker npm test 

after_success:
  - docker build -t debasishk/multi-client ./client
  - docker build -t debasishk/multi-nginx ./nginx
  - docker build -t debasishk/multi-server ./server
  - docker build -t debasishk/multi-worker ./worker

#Docker Hub docker cli Login 
  - echo "$DOCKER_KEY" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push debasishk/multi-client
  - docker push debasishk/multi-nginx
  - docker push debasishk/multi-server
  - docker push debasishk/multi-worker

# Let EBS know goahead and pull images from Dockerhub to deploy. 
# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-187968103495
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
     
